import type { Metadata } from "next";
import "./globals.css";
import {
  Inter,
  JetBrains_Mono,
  Roboto_Slab,
  Public_Sans,
  Manrope,
} from "next/font/google";
import { QueryProvider } from "@/providers/QueryProvider";
import ToastProvider from "@/providers/ToastProvider";
import { cn } from "@/lib/utils";
import ModalProvider from "@/providers/ModalProvider";

const publicSansHeading = Public_Sans({
  subsets: ["latin"],
  variable: "--public-sans",
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--roboto-slab",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const manrope = Manrope({
  variable: "--manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "ScholarHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "scrollbar-thin",
        "font-serif",
        inter.variable,
        manrope.variable,
        robotoSlab.variable,
        publicSansHeading.variable,
      )}
    >
      <body
        className={`antialiased`}
      >
        <ToastProvider />
        <QueryProvider>
          <ModalProvider/>
          {children}</QueryProvider>
      </body>
    </html>
  );
}
